### ISSUE TITLE
How to produce Figure1

### ISSUE THREAD

**Issue by likanchuan** [dvirsamuel/DRO-LT#4]
Hi!Thank you for sharing your awsome work. The elegent diagram in Figure1 of the paper draws my interest. Could you please share how you produced it or what software you used? Or is it a tutorial for it? I'm looking forward to your reply.

Best wishes

**Comment by dvirsamuel** [comment]
Hi,
Thank you for your kind words.
We actually used power-point to create the figures :)
No clever software was used here.
